const funcion = require("./calculadora")

let sumar = funcion.sumar(2,3)
console.log(sumar)
let restar = funcion.restar(2,3)
console.log(restar)
let multiplicar = funcion.multiplicar(2,3)
console.log(multiplicar)
let dividir = funcion.dividir(2,3)
console.log(dividir)